mqtt:
#  # TLS parameters.
#  tls:
#    ca_certs: <path_to_your_root_certificate>
#    certfile: <path_to_your_key_certificate>
#    keyfile: <your_path_to_private_key>
#    tls_version: 5
#    tls_insecure: false

  # Connection parameters.
  connection:
    host: 127.0.0.1
    port: 1883
    keepalive: 60

  # MQTT parameters.
  client:
    protocol: 5
    client_id: client_test_1

bridge:
  # Bridge from ROS to MQTT.
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vda5050_msgs.msg:State
    topic_from: /state
    topic_to: qa/client_test_1/state

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vda5050_msgs.msg:Visualization
    topic_from: /visualization
    topic_to: qa/client_test_1/visualization

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vda5050_msgs.msg:Connection
    topic_from: /connection
    topic_to: qa/client_test_1/connection

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vda5050_msgs.msg:FactSheet
    topic_from: /factSheet
    topic_to: qa/client_test_1/factSheet

  # Bridge from MQTT to ROS.
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: vda5050_msgs.msg:InstantAction
    topic_from: qa/client_test_1/instantAction
    topic_to: /ia_from_mc

  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: vda5050_msgs.msg:Order
    topic_from: qa/client_test_1/order
    topic_to: /order_from_mc

  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: vda5050_msgs.msg:MapUpdate
    topic_from: qa/client_test_1/map
    topic_to: /map

  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: vda5050_msgs.msg:ZoneUpdate
    topic_from: qa/client_test_1/zones
    topic_to: /zones

serializer: json:dumps
deserializer: json:loads