state_daemon:
    topics_publish:
        state: /state
    topics_subscribe:
        orderId: "/TBD2"
        orderUpdateId: "/TBD3"                  #VDA5050 specific, Uint32
        zoneSetId: "/TBD4"                      #VDA5050 specific, string
        lastNodeId: "/TBD5"                     #VDA5050 specific, string
        lastNodeSequenceId: "/TBD6"             #VDA5050 specific, Uint32
        nodeState: "/TBD7"                      #VDA5050 specific, array
            # ADD nodeState	
        edgeState: "/TBD8"                      #VDA5050 specific, array
            # ADD edgeState
        agvPosition:                    	#VDA5050 specific + partially covered by ROS common msg, JSON
            positionInitialized: "/TBD10"       #VDA5050 specific, boolean
            localizationScore: "/TBD11"         #VDA5050 specific, float64 (Range 0.0-1.0)
            deviationRange: "/TBD12"            #VDA5050 specific, float64
            x: "/TBD13"                         #ROS msg -> nav_msgs/Odometry Message.pose.pose.position.x, float64
            y: "/TBD14"                         #ROS msg -> nav_msgs/Odometry Message.pose.pose.position.y, float64
            theta: "/TBD15"
            mapID: "/TBD16"                     #VDA5050 specific, string
            mapDescription: "/TBD17"            #VDA5050 specific, string
        velocity:                               #ROS msg -> nav_msgs/Odometry Message.twist, aggregarted by ROS msg
            vx: "/TBD19"                        #ROS msg -> nav_msgs/Odometry Message.twist.twist.linear.x, float64
            vy: "/TBD20"                        #ROS msg -> nav_msgs/Odometry Message.twist.twist.linear.y, float64
            omega: "/TBD21"
        loads: "/TBD22"                         #VDA5050 specific, array
            # ADD loads
        driving: "/TBD23"                       #VDA5050 specific, boolean
        paused: "/TBD10"                        #VDA5050 specific, boolean
        newBaseRequest: "/TBD10"		#VDA5050 specific, boolean
        distanceSinceLastNode: "/TBD10"		#VDA5050 specific, float64
        actionStates: "/TBD10"			#VDA5050 specific, array
            # ADD actionStates
        batteryState:				#VDA5050 specific + partially covered by ROS common msg, JSON
            batteryCharge: "/TBD10"		#ROS msg -> sensor_msgs/Batterystate Message.percentage
            batteryVoltage: "/TBD10"		#ROS msg -> sensor_msgs/Batterystate Message.voltage
            batteryHealth: "/TBD10"		#VDA5050 specific, int8
            charging: "/TBD10"			#VDA5050 specific, bool
            reach: "/TBD10"			#VDA5050 specific, uint32
        operatingMode: "/TBD999"		#VDA5050 specific, string
        errors: "/ERROR4389"
            # ADD error
        information: "/TBD10"
            # ADD info
        safetyState:
            eStop: "/TBD999"
            fieldViolation: "/TBD999"

topic_error: /error_1

AGV_Data:
    version: 1.1.03
    manufacturer: "template_1"
    serialNumber: "AGV721"




