###### bridge from ROS to MQTT ######

- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: vda5050_msgs.msg:State
  topic_from: /state
  topic_to: master/state
  
###### bridge from MQTT to ROS ######

- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: vda5050_msgs.msg:Order
  topic_from: master/order
  topic_to: /order
