
# TLS parameters
tls:
  ca_certs: /home/rothmeyer/VDA5050/TUM_Certs/rootCA.crt
  certfile: /home/rothmeyer/VDA5050/TUM_Certs/tum_florian-certificate.pem.crt
  keyfile: /home/rothmeyer/VDA5050/TUM_Certs/tum_florian-private.pem.key
  tls_version: 5
  tls_insecure: false
  
# Connection parameters
connection:
  host: ahmj34rbzc71v-ats.iot.eu-central-1.amazonaws.com
  port: 8883
  keepalive: 60

# MQTT parameters
client:
  # User MQTT311
  protocol: 4
  client_id: tum_florian
