###### bridge from ROS to MQTT ######

- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: std_msgs.msg:String
  topic_from: /test
  topic_to: tum/tum_florian/test
  
###### bridge from MQTT to ROS ######

- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: std_msgs.msg:String
  topic_from: tum/tum_florian/echo
  topic_to: /echo
